"""Bakes the weapon types' animations (weapon_types.py) for the game.

    python3 export_types.py            -> ReplicatedStorage/WeaponClips.lua
    python3 export_types.py --rbxmx    ... and ServerStorage/WeaponAnimations.rbxmx too

WeaponClips.lua is what the game plays: WeaponFX drives every R6 joint from
it on every screen (no uploading, no ids). Each clip is every joint's
Motor6D.Transform, frame by frame - swings at 60 a second, idles at 30 - as
quaternions (x, y, z, w; the body's also its height), with the moments the
game needs: when the cut starts and ends (the smear), and the hit.

The .rbxmx has the same animations as KeyframeSequences, only if you want
to open them in Studio's Animation Editor and publish them (see README.md:
"Into the game" - the same steps as the sword's). It's big, so it isn't
made unless asked for.
"""
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import anims  # noqa: E402
import weapon_types as wt  # noqa: E402

ROOT = os.path.join(HERE, '..', '..')
JOINTS = [('Root', 'RootJoint'), ('Neck', 'Neck'), ('RS', 'Right Shoulder'), ('LS', 'Left Shoulder'),
          ('RH', 'Right Hip'), ('LH', 'Left Hip'), ('Grip', 'Grip')]


def quat(m):
    """a rotation matrix as a quaternion (x, y, z, w), w >= 0"""
    r = m[:3, :3]
    tr = r[0, 0] + r[1, 1] + r[2, 2]
    if tr > 0:
        s = math.sqrt(tr + 1.0) * 2
        w, x, y, z = 0.25 * s, (r[2, 1] - r[1, 2]) / s, (r[0, 2] - r[2, 0]) / s, (r[1, 0] - r[0, 1]) / s
    elif r[0, 0] > r[1, 1] and r[0, 0] > r[2, 2]:
        s = math.sqrt(1.0 + r[0, 0] - r[1, 1] - r[2, 2]) * 2
        w, x, y, z = (r[2, 1] - r[1, 2]) / s, 0.25 * s, (r[0, 1] + r[1, 0]) / s, (r[0, 2] + r[2, 0]) / s
    elif r[1, 1] > r[2, 2]:
        s = math.sqrt(1.0 + r[1, 1] - r[0, 0] - r[2, 2]) * 2
        w, x, y, z = (r[0, 2] - r[2, 0]) / s, (r[0, 1] + r[1, 0]) / s, 0.25 * s, (r[1, 2] + r[2, 1]) / s
    else:
        s = math.sqrt(1.0 + r[2, 2] - r[0, 0] - r[1, 1]) * 2
        w, x, y, z = (r[1, 0] - r[0, 1]) / s, (r[0, 2] + r[2, 0]) / s, (r[1, 2] + r[2, 1]) / s, 0.25 * s
    q = np.array([x, y, z, w])
    q /= np.linalg.norm(q)
    return q if q[3] >= 0 else -q


def num(x):
    s = '%.4f' % x
    s = s.rstrip('0').rstrip('.')
    return '0' if s in ('-0', '') else s


def bake(anim, fps):
    n = int(round(anim.length * fps))
    count = n if anim.loop else n + 1
    rows = {key: [] for key, _ in JOINTS}
    for i in range(count):
        tr = anims.dir_transforms(anim.at(i / fps))
        for key, joint in JOINTS:
            m = tr[joint]
            q = quat(m)
            vals = list(q)
            if key == 'Root':
                vals.append(m[2, 3])  # (the body's height: the RootJoint's frame has Z up)
            rows[key].append(','.join(num(v) for v in vals))
    return count, {key: ';'.join(v) for key, v in rows.items()}


def clip_lua(anim, fps, indent, extra):
    count, rows = bake(anim, fps)
    pad = '\t' * indent
    out = [pad + '{']
    out.append(pad + '\tname = "%s", fps = %d, frames = %d, length = %s, loop = %s,' % (
        anim.name, fps, count, num(anim.length), 'true' if anim.loop else 'false'))
    for k, v in extra.items():
        out.append(pad + '\t%s = %s,' % (k, num(v)))
    out.append(pad + '\tjoints = {')
    for key, _ in JOINTS:
        out.append(pad + '\t\t%s = "%s",' % (key, rows[key]))
    out.append(pad + '\t},')
    out.append(pad + '}')
    return '\n'.join(out)


def main():
    lines = ['-- GENERATED by Tools/Animations/export_types.py from weapon_types.py - change the',
             "-- animations there and run it again; don't edit this by hand.",
             '--',
             '-- The weapon types\' animations, baked: WeaponFX plays them on every R6 joint (see',
             '-- its "Clips"). Each joint is a list of frames "x,y,z,w;..." (a quaternion; the',
             "-- body's Root has its height after it). cut / through: when the smear shows;",
             '-- hit: the moment the server cuts (Config.Weapons.Types: Lock x Contact).',
             'return {']
    for kind, names in wt.STRINGS.items():
        lines.append('\t%s = {' % kind)
        if kind in wt.OFFHAND:
            tilt, roll = wt.OFFHAND[kind]
            lines.append('\t\tOffhand = { %s, %s },' % (num(tilt), num(roll)))
        if any(getattr(wt.ANIMS[n], 'two', None) is not None for n in names[1:]):
            lines.append('\t\tTwoHanded = true,')
        lines.append('\t\tIdle = ' + clip_lua(wt.ANIMS[names[0]], 30, 2, {}).lstrip() + ',')
        lines.append('\t\tSwings = {')
        for name in names[1:]:
            s = wt.ANIMS[name]
            extra = {'hit': s.hit, 'lock': s.lock, 'cut': s.trail[0], 'through': s.trail[1]}
            lines.append(clip_lua(s, 60, 3, extra) + ',')
        lines.append('\t\t},')
        lines.append('\t},')
    lines.append('}')
    path = os.path.join(ROOT, 'ReplicatedStorage', 'WeaponClips.lua')
    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('saved', os.path.normpath(path), os.path.getsize(path) // 1024, 'KB')

    if '--rbxmx' in sys.argv:
        import export_rbxmx as ex
        for kind, names in wt.STRINGS.items():
            for name in names[1:]:
                s = wt.ANIMS[name]
                ex.MARKERS[name] = [('Cut', s.trail[0]), ('Hit', s.hit), ('Through', s.trail[1])]
        head = ('<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" '
                'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
                'xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">')
        body = ['\t<Item class="Folder" referent="%s">' % ex.ref(), '\t\t<Properties>',
                '\t\t\t<string name="Name">WeaponAnimations</string>', '\t\t</Properties>']
        for kind, names in wt.STRINGS.items():
            for name in names:
                body.append(ex.sequence_xml(wt.ANIMS[name], 2))
        body.append('\t</Item>')
        out = os.path.join(ROOT, 'ServerStorage', 'WeaponAnimations.rbxmx')
        with open(out, 'w') as f:
            f.write(head + '\n' + '\n'.join(body) + '\n</roblox>\n')
        print('saved', os.path.normpath(out), os.path.getsize(out) // 1024, 'KB')


if __name__ == '__main__':
    main()
