-- GENERATED by Tools/Weapons/make_models.py from Tools/Weapons/packs - change
-- the weapons there and run it again; don't edit this by hand.
--
-- The voxel weapons' 3D models: each one is a mesh per material (a
-- MeshPart named after it) plus three markers - GripMark (the middle of
-- the grip), TipMark (Tip studs up the weapon) and UpMark (Up studs to
-- its front: the handle's +Y) - so the game holds it exactly like the
-- blocky stand-in. The models themselves come in by upload
-- (Tools/Upload/upload_assets.bat: their ids go in ReplicatedStorage/AssetIds,
-- and the server loads them into ReplicatedStorage > WeaponModels) or by
-- hand (Studio's 3D Importer, into that WeaponModels folder).
-- Parts: how each mesh is coloured (Role "metal" turns gold when the
-- weapon awakens at mastery 100, "glow" is Neon in the smear's colour).
return {
	GooGloves = {
		Name = "Goo Gloves", Type = "Fists", Pack = "Slime", Rarity = "Common",
		Tip = 1, Up = 1, -- (the markers: studs from the grip, up the weapon and to its front)
		Size = { 1.3, 1.3, 1.9 }, -- (studs: across X, across Y, its length)
		Glow = { 110, 230, 90 },
		Smear = { { 0, 0, 0.4 }, { 0, 0, -0.9 } }, -- (the handle's own space: -Z up the weapon)
		SmearWide = { { 0, 0, 0.4 }, { 0, 0, -0.9 } },
		Head = { 0, 0, -0.6 }, -- (the business end: a hammer's head, a blade's tip)
		Parts = {
			bubble = { Color = { 235, 255, 225 }, Material = "SmoothPlastic", Transparency = 0.5, Role = "body" },
			core = { Color = { 26, 38, 22 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			eye = { Color = { 255, 255, 255 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			goo = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			pupil = { Color = { 24, 20, 37 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			slime = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			slime_d = { Color = { 46, 120, 40 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			slime_l = { Color = { 150, 223, 125 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
		},
	},
	Jellyblade = {
		Name = "Jellyblade", Type = "Sword", Pack = "Slime", Rarity = "Rare",
		Tip = 1, Up = 1, -- (the markers: studs from the grip, up the weapon and to its front)
		Size = { 0.5, 1.7, 5.9 }, -- (studs: across X, across Y, its length)
		Glow = { 214, 255, 120 },
		Smear = { { 0, 0, -1.2 }, { 0, 0, -4.6 } }, -- (the handle's own space: -Z up the weapon)
		SmearWide = { { 0, 0, -0.9 }, { 0, 0, -4.8 } },
		Head = { 0, 0, -4.75 }, -- (the business end: a hammer's head, a blade's tip)
		Parts = {
			bone = { Color = { 234, 212, 170 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			bubble = { Color = { 235, 255, 225 }, Material = "SmoothPlastic", Transparency = 0.5, Role = "body" },
			eye = { Color = { 255, 255, 255 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			goo = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			goo_l = { Color = { 165, 228, 144 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			grip = { Color = { 30, 80, 40 }, Material = "SmoothPlastic", Transparency = 0, Role = "grip" },
			grip_l = { Color = { 46, 120, 40 }, Material = "SmoothPlastic", Transparency = 0, Role = "grip" },
			heart = { Color = { 214, 255, 120 }, Material = "Neon", Transparency = 0, Role = "glow" },
			pupil = { Color = { 24, 20, 37 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			slime = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			slime_l = { Color = { 150, 223, 125 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
		},
	},
	GelatinHammer = {
		Name = "Gelatin Hammer", Type = "Hammer", Pack = "Slime", Rarity = "Epic",
		Tip = 1, Up = 1, -- (the markers: studs from the grip, up the weapon and to its front)
		Size = { 2.6, 1.7, 5.9 }, -- (studs: across X, across Y, its length)
		Glow = { 214, 255, 120 },
		Smear = { { -1.3, 0, -3.8 }, { 1.3, 0, -3.8 } }, -- (the handle's own space: -Z up the weapon)
		SmearWide = { { -1.5, 0, -3.8 }, { 1.5, 0, -3.8 } },
		Head = { 0, 0, -3.95 }, -- (the business end: a hammer's head, a blade's tip)
		Parts = {
			bubble = { Color = { 235, 255, 225 }, Material = "SmoothPlastic", Transparency = 0.5, Role = "body" },
			core = { Color = { 26, 38, 22 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			eye = { Color = { 255, 255, 255 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			goo = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			goo_d = { Color = { 46, 120, 40 }, Material = "SmoothPlastic", Transparency = 0.3, Role = "body" },
			goo_l = { Color = { 165, 228, 144 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			heart = { Color = { 214, 255, 120 }, Material = "Neon", Transparency = 0, Role = "glow" },
			pupil = { Color = { 24, 20, 37 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			slime_d = { Color = { 46, 120, 40 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			steel = { Color = { 139, 155, 180 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			steel_d = { Color = { 90, 105, 136 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			steel_l = { Color = { 192, 203, 220 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			wood = { Color = { 115, 62, 57 }, Material = "SmoothPlastic", Transparency = 0, Role = "grip" },
			wood_l = { Color = { 184, 111, 80 }, Material = "SmoothPlastic", Transparency = 0, Role = "grip" },
		},
	},
	OozeDaggers = {
		Name = "Ooze Daggers", Type = "Daggers", Pack = "Slime", Rarity = "Legendary",
		Tip = 1, Up = 1, -- (the markers: studs from the grip, up the weapon and to its front)
		Size = { 0.3, 1.1, 3.2 }, -- (studs: across X, across Y, its length)
		Glow = { 120, 255, 60 },
		Smear = { { 0, 0, -0.6 }, { 0, 0, -2.5 } }, -- (the handle's own space: -Z up the weapon)
		SmearWide = { { 0, 0, -0.4 }, { 0, 0, -2.6 } },
		Head = { 0, 0, -2.55 }, -- (the business end: a hammer's head, a blade's tip)
		Parts = {
			acid = { Color = { 120, 255, 60 }, Material = "Neon", Transparency = 0, Role = "glow" },
			goo = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			heart = { Color = { 214, 255, 120 }, Material = "Neon", Transparency = 0, Role = "glow" },
			obsid = { Color = { 25, 60, 62 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			obsid_d = { Color = { 14, 30, 28 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			obsid_l = { Color = { 44, 104, 96 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
		},
	},
	AcidScythe = {
		Name = "Acid Scythe", Type = "Scythe", Pack = "Slime", Rarity = "Mythic",
		Tip = 1, Up = 1, -- (the markers: studs from the grip, up the weapon and to its front)
		Size = { 4.3, 0.5, 7.4 }, -- (studs: across X, across Y, its length)
		Glow = { 120, 255, 60 },
		Smear = { { 0.4, 0, -5.2 }, { 3.9, 0, -4 } }, -- (the handle's own space: -Z up the weapon)
		SmearWide = { { 0.2, 0, -5.4 }, { 4.1, 0, -3.9 } },
		Head = { 0, 0, -5.95 }, -- (the business end: a hammer's head, a blade's tip)
		Parts = {
			acid = { Color = { 120, 255, 60 }, Material = "Neon", Transparency = 0, Role = "glow" },
			goo = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			heart = { Color = { 214, 255, 120 }, Material = "Neon", Transparency = 0, Role = "glow" },
			iron = { Color = { 58, 68, 102 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			iron_d = { Color = { 38, 43, 68 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			slime = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			slime_l = { Color = { 150, 223, 125 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			steel = { Color = { 139, 155, 180 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			steel_d = { Color = { 90, 105, 136 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
			steel_l = { Color = { 192, 203, 220 }, Material = "SmoothPlastic", Transparency = 0, Role = "metal" },
		},
	},
	GelatinousEdge = {
		Name = "Gelatinous Edge", Type = "Katana", Pack = "Slime", Rarity = "Secret",
		Tip = 1, Up = 1, -- (the markers: studs from the grip, up the weapon and to its front)
		Size = { 0.7, 0.9, 6.6 }, -- (studs: across X, across Y, its length)
		Glow = { 120, 255, 60 },
		Smear = { { 0, 0, -1.4 }, { 0, 0, -5.5 } }, -- (the handle's own space: -Z up the weapon)
		SmearWide = { { 0, 0, -1 }, { 0, 0, -5.7 } },
		Head = { 0, 0, -5.65 }, -- (the business end: a hammer's head, a blade's tip)
		Parts = {
			acid = { Color = { 120, 255, 60 }, Material = "Neon", Transparency = 0, Role = "glow" },
			bubble = { Color = { 235, 255, 225 }, Material = "SmoothPlastic", Transparency = 0.5, Role = "body" },
			core = { Color = { 26, 38, 22 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			eyeglow = { Color = { 236, 255, 170 }, Material = "Neon", Transparency = 0, Role = "glow" },
			gold = { Color = { 254, 174, 52 }, Material = "SmoothPlastic", Transparency = 0, Role = "trim" },
			gold_l = { Color = { 254, 231, 97 }, Material = "SmoothPlastic", Transparency = 0, Role = "trim" },
			goo = { Color = { 105, 210, 70 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			goo_d = { Color = { 46, 120, 40 }, Material = "SmoothPlastic", Transparency = 0.3, Role = "body" },
			goo_l = { Color = { 165, 228, 144 }, Material = "SmoothPlastic", Transparency = 0.35, Role = "body" },
			grip = { Color = { 30, 80, 40 }, Material = "SmoothPlastic", Transparency = 0, Role = "grip" },
			heart = { Color = { 214, 255, 120 }, Material = "Neon", Transparency = 0, Role = "glow" },
			stone = { Color = { 128, 124, 116 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
			stone_d = { Color = { 88, 86, 82 }, Material = "SmoothPlastic", Transparency = 0, Role = "body" },
		},
	},
}
